package jetbrains.mps.kotlin.test.scopes;

/*Generated by MPS */

import jetbrains.mps.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.jupiter.api.extension.RegisterExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCacheExtension;
import jetbrains.mps.lang.test.runtime.TestParametersCache;
import org.junit.jupiter.api.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.lang.test.runtime.TransformationTest;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.test.runtime.CheckExpectedMessageRunnable;
import jetbrains.mps.errors.MessageStatus;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.lang.test.runtime.CheckErrorMessagesRunnable;
import java.util.Arrays;

@MPSLaunch
public class InstanceVisibility_Test extends BaseTransformationTest {
  @RegisterExtension
  private static final TestParametersCacheExtension ourParametersCacheExtension = new TestParametersCacheExtension(new TestParametersCache(InstanceVisibility_Test.class, "${kotlin_home}", "r:5496351e-6e92-4051-85ca-98be7df49c2e(jetbrains.mps.kotlin.test.scopes@tests)", false));

  public InstanceVisibility_Test() {
    super(ourParametersCacheExtension.getParametersCache());
  }

  @Test
  public void test_NodeUnknownRuleCheck2138970093538338453() throws Throwable {
    new TestBody(this).test_NodeUnknownRuleCheck2138970093538338453();
  }
  @Test
  public void test_NodeUnknownRuleCheck2138970093538347119() throws Throwable {
    new TestBody(this).test_NodeUnknownRuleCheck2138970093538347119();
  }
  @Test
  public void test_NodeUnknownRuleCheck2138970093538355843() throws Throwable {
    new TestBody(this).test_NodeUnknownRuleCheck2138970093538355843();
  }
  @Test
  public void test_ErrorMessagesCheck2138970093538323889() throws Throwable {
    new TestBody(this).test_ErrorMessagesCheck2138970093538323889();
  }

  /*package*/ static class TestBody extends BaseTestBody {

    /*package*/ TestBody(TransformationTest owner) {
      super(owner);
    }

    @Override
    protected void initTestNodes() {
      prepareTestNodes("2138970093538317250");
    }

    public void test_NodeUnknownRuleCheck2138970093538338453() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        SNode nodeToCheck = getNodeById("5491524000827280415");
        new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(nodeToCheck, MessageStatus.ERROR, new SNodePointer("r:133e8cac-c6ad-447f-a90c-5146ca3b1aed(jetbrains.mps.kotlin.constraints)", "4662566628538085344"), "", myProject.getRepository(), myProject.getPlatform()).run();
      });
    }
    public void test_NodeUnknownRuleCheck2138970093538347119() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        SNode nodeToCheck = getNodeById("5491524000826908999");
        new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(nodeToCheck, MessageStatus.ERROR, new SNodePointer("r:133e8cac-c6ad-447f-a90c-5146ca3b1aed(jetbrains.mps.kotlin.constraints)", "4662566628538085344"), "", myProject.getRepository(), myProject.getPlatform()).run();
      });
    }
    public void test_NodeUnknownRuleCheck2138970093538355843() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        SNode nodeToCheck = getNodeById("5491524000826909002");
        new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(nodeToCheck, MessageStatus.ERROR, new SNodePointer("r:133e8cac-c6ad-447f-a90c-5146ca3b1aed(jetbrains.mps.kotlin.constraints)", "4662566628538085344"), "", myProject.getRepository(), myProject.getPlatform()).run();
      });
    }
    public void test_ErrorMessagesCheck2138970093538323889() throws Exception {
      initTestNodes();
      runWithinCommand(() -> {
        SNode nodeToCheck = getNodeById("5491524000824249752");
        new CheckErrorMessagesRunnable(nodeToCheck, false, false, myProject.getPlatform()).includeSelf(true).exclude(Arrays.<CheckExpectedMessageRunnable>asList(new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(getNodeById("5491524000827280415"), MessageStatus.ERROR, new SNodePointer("r:133e8cac-c6ad-447f-a90c-5146ca3b1aed(jetbrains.mps.kotlin.constraints)", "4662566628538085344"), "", myProject.getRepository(), myProject.getPlatform()), new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(getNodeById("5491524000826908999"), MessageStatus.ERROR, new SNodePointer("r:133e8cac-c6ad-447f-a90c-5146ca3b1aed(jetbrains.mps.kotlin.constraints)", "4662566628538085344"), "", myProject.getRepository(), myProject.getPlatform()), new CheckExpectedMessageRunnable.CheckExpectedRuleMessageRunnable(getNodeById("5491524000826909002"), MessageStatus.ERROR, new SNodePointer("r:133e8cac-c6ad-447f-a90c-5146ca3b1aed(jetbrains.mps.kotlin.constraints)", "4662566628538085344"), "", myProject.getRepository(), myProject.getPlatform()))).run();
      });
    }

  }
}
