package jetbrains.mps.kotlin.test.runtime;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.Objects;

public class Post {
  public List<Object> messages = new ArrayList<>();

  public void process(Message message) {
    ListSequence.fromList(messages).addElement(message);
  }

  public Message searchFor(final String pattern) {
    // TODO these cast are necessary because generation wants to coerce to ClassifierType (which is going to be a major annoyance for using kotlin in BL)
    return (Message) ListSequence.fromList(messages).findFirst((message) -> Objects.equals(((Message) message).open(), pattern));
  }
}
