# Build configuration on TeamCity for MPS
mpsBuildConfiguration=MPS_20261_Distribution_DownloadableArtifacts
mpsBuildArtifact=MPS-261.23567.135


# Build configuration on TeamCity for coderules
coderulesBuildConfiguration=MPS_20261_Distribution_MpsCodeRules
coderulesBuildArtifact=MPS-261.23567.141-1295


# Release number
mpsRelease=2026.1 EAP

# Dependencies for build
mpsLocation=../deps/mps
coderulesLocation=../deps/coderules
jdkLocation=

org.gradle.logging.level=info
